services:
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        environment:
            - Backend_URL=http://backend:8080
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "8080:8080"
